name: Build Windows packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.runner }}
    container: ${{ matrix.container }}
    name: "os:${{matrix.config.os}} | v:${{matrix.config.version}} (pre-cxx11: ${{matrix.precxx11abi }})"
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        
        config: 
          # when changing supported versions here, please modify supported versions
          # in install.R

          - {os: windows, version: cpu}
          - {os: windows, version: cu12.4}
        
        precxx11abi: [0, 1]

        include:
          - config: {version: cu12.4}
            cuda: 12.4
            cuda_patch: 1

        exclude:
          - config: {os: windows}
            precxx11abi: 1
        
    env:
      CUDA: ${{ matrix.cuda }}
      PRECXX11ABI: ${{ matrix.precxx11abi }}
      
    steps:

      - name: Install system dependencies
        if: matrix.container != ''
        run: |
          DEBIAN_FRONTEND="noninteractive" apt-get update
          DEBIAN_FRONTEND="noninteractive" apt-get install -y curl sudo libxml2-dev wget chrpath rsync git build-essential
          curl -fsSL https://get.docker.com -o get-docker.sh
          DRY_RUN=1 sh ./get-docker.sh

      - uses: actions/checkout@v4
      
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.25.1"

      - name: Install CUDA
        if: ${{matrix.cuda != ''}}
        uses: Jimver/cuda-toolkit@v0.2.22
        id: cuda-toolkit
        with:
          cuda: "${{matrix.cuda}}.${{matrix.cuda_patch}}"
          log-file-suffix: '${{matrix.cuda}}.${{matrix.cuda_patch}}.${{matrix.precxx11abi}}.txt'
          
      - name: Install CuDNN
        if: ${{ matrix.cuda != '' }}
        uses: ./.github/actions/install-cudnn
        with:
          cuda_version: ${{ matrix.cuda }}

      - name: Run cmake
        run: |
          cd src/lantern/
          mkdir build
          cd build
          cmake ..

      - name: Build libs
        id: build
        run: |
          cd src/lantern/build
          cmake --build . --config Release --parallel 4 --target package
          fname=$(ls . | grep "lantern.*\.zip")
          echo "fname=$fname" >> $GITHUB_OUTPUT
        shell: bash

      - id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.fname }}
          path: 'src/lantern/build/${{ steps.build.outputs.fname }}'
      
      
